# Generated by Django 4.0.2 on 2022-02-09 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='works',
            options={'verbose_name_plural': 'Works'},
        ),
    ]
